"""complete prescription schema

Revision ID: 1adcb2f8f39c
Revises: 51d4caa79689
Create Date: 2026-07-09 19:56:29.632914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1adcb2f8f39c'
down_revision = '51d4caa79689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('morning',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('afternoon',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('night',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_prescription_items_medicine_id'), ['medicine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescription_items_prescription_id'), ['prescription_id'], unique=False)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('prescription_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_record_id'), ['record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_record_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_doctor_id'))
        batch_op.alter_column('prescription_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_items_prescription_id'))
        batch_op.drop_index(batch_op.f('ix_prescription_items_medicine_id'))
        batch_op.alter_column('night',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('afternoon',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('morning',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
