"""add insurance table

Revision ID: 3db107f6da1f
Revises: 1adcb2f8f39c
Create Date: 2026-07-09 21:32:45.794036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db107f6da1f'
down_revision = '1adcb2f8f39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=150), nullable=False),
    sa.Column('policy_number', sa.String(length=150), nullable=False),
    sa.Column('coverage_type', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_number'),
    sa.UniqueConstraint('provider')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance')
    # ### end Alembic commands ###
