"""add settings table

Revision ID: d13bed35493c
Revises: 3db107f6da1f
Create Date: 2026-07-09 21:45:08.590213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13bed35493c'
down_revision = '3db107f6da1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(length=150), nullable=False),
    sa.Column('hospital_address', sa.Text(), nullable=True),
    sa.Column('hospital_phone', sa.String(length=30), nullable=True),
    sa.Column('hospital_email', sa.String(length=150), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
